# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17AwzThO2zjgrQa6C8jbE2qjB0u8kqRSU
"""

import streamlit as st
import joblib
import numpy as np

# ----------------------------
# Page config
# ----------------------------
st.set_page_config(
    page_title="SMS Spam Detector",
    page_icon="📩",
    layout="centered"
)

st.title("📩 SMS Spam Detector")
st.write(
    "This app classifies an SMS message as **Spam** or **Ham (Legit)** using an NLP model trained with TF-IDF + a classifier."
)

# ----------------------------
# Load model (cached)
# ----------------------------
@st.cache_resource
def load_model():
    return joblib.load("models/spam_detector_calibrated_svm.joblib")

model = load_model()

# ----------------------------
# UI
# ----------------------------
sms = st.text_area(
    "Enter an SMS message:",
    placeholder="e.g., WIN a FREE iPhone now! Click here...",
    height=140
)

col1, col2 = st.columns([1, 1])

with col1:
    predict_btn = st.button("Predict", type="primary")

with col2:
    clear_btn = st.button("Clear")

if clear_btn:
    st.experimental_rerun()

# ----------------------------
# Prediction
# ----------------------------
if predict_btn:
    if not sms.strip():
        st.warning("Please enter a message first.")
    else:
        pred = model.predict([sms])[0]

        # Some pipelines have predict_proba; calibrated models usually do.
        proba = None
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba([sms])[0]
            # assume classes are ["ham","spam"] or similar
            classes = list(model.classes_)
            spam_index = classes.index("spam") if "spam" in classes else int(np.argmax(proba))

        if pred == "spam":
            st.error("🚨 Prediction: **SPAM**")
        else:
            st.success("✅ Prediction: **HAM (Legit)**")

        if proba is not None:
            st.write("### Confidence")
            if "spam" in model.classes_:
                spam_prob = proba[spam_index]
                st.progress(float(spam_prob))
                st.caption(f"Spam probability: **{spam_prob:.2%}**")
            else:
                st.write(dict(zip(model.classes_, proba)))

        st.write("### Notes")
        st.info(
            "This is a machine learning prediction. Always be cautious with links, requests for money, or urgent messages."
        )
